export enum Permissions {
  Admin = 'admin',
  Assets = 'assets',
  ViewAssets = 'assets.view',
  UploadAssets = 'assets.upload',
  RemoveAssets = 'assets.remove',
  Contacts = 'contacts',
  ViewContacts = 'contacts.view',
  RemoveContacts = 'contacts.remove',
  Orders = 'orders',
  ViewOrders = 'orders.view',
  Products = 'products',
  ViewProducts = 'products.view',
  ManageProducts = 'products.manage',
  RemoveProducts = 'products.remove',
}
